import { CborValue, InferFailure, decodeCanonicalCbor } from "./cbor.js";

const KINDS: Record<string, { required: string[]; optional: string[] }> = {
  "knolo.infer.model-image": {
    required: [
      "architecture",
      "capabilities",
      "extensions",
      "generationDefaults",
      "kind",
      "license",
      "name",
      "precisions",
      "requirements",
      "signatures",
      "sources",
      "specialTokens",
      "template",
      "tensorInventory",
      "tokenizer",
      "variant",
      "version",
      "weights",
    ],
    optional: ["placementHints"],
  },
  "knolo.infer.model-artifact-set": { required: ["extensions", "files", "kind", "version"], optional: [] },
  "knolo.infer.engine-build": {
    required: [
      "binarySha256",
      "buildProfile",
      "cargoLockRoot",
      "extensions",
      "featureSet",
      "kernelBundleRoot",
      "kind",
      "rustcVersion",
      "sourceCommit",
      "targetTriple",
      "tensorBackend",
      "tensorBackendVersion",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.kernel-bundle": {
    required: [
      "buildMode",
      "codeObjectRoot",
      "compilerFlags",
      "cudaArchitectures",
      "cudaToolkitVersion",
      "extensions",
      "kind",
      "sourceRoot",
      "version",
    ],
    optional: ["jit"],
  },
  "knolo.infer.hardware-probe": {
    required: [
      "cpuArchitecture",
      "cpuModelClass",
      "extensions",
      "gpus",
      "kernelBundles",
      "kind",
      "logicalCores",
      "physicalCores",
      "ramAvailableBytes",
      "ramTotalBytes",
      "storageAvailableBytes",
      "storageClass",
      "version",
    ],
    optional: ["numaNodeCount"],
  },
  "knolo.infer.placement-plan": {
    required: [
      "contextReservationTokens",
      "devices",
      "expectedKvBytes",
      "expectedOverheadBytes",
      "expectedStagingBytes",
      "expectedTotalBytes",
      "expectedWeightBytes",
      "expectedWorkspaceBytes",
      "extensions",
      "graphCaptureMode",
      "kind",
      "kvBlockSize",
      "kvPrecision",
      "modelRuntimeRoot",
      "safetyMarginBytes",
      "tensorGroups",
      "version",
      "workspaceBytes",
    ],
    optional: ["rejectionReason"],
  },
  "knolo.infer.prompt-input": {
    required: ["extensions", "kind", "messages", "version"],
    optional: ["evidence", "systemPolicy", "toolsRoot"],
  },
  "knolo.infer.prompt-plan": {
    required: [
      "extensions",
      "kind",
      "messagesRoot",
      "renderedText",
      "specialTokenPlanRoot",
      "templateRoot",
      "tokenIds",
      "tokenizerRoot",
      "truncation",
      "version",
    ],
    optional: ["evidenceRoot", "toolsRoot"],
  },
  "knolo.infer.evidence-binding": {
    required: ["contextRoot", "extensions", "kind", "orderedEvidenceIds", "queryReceiptIds", "reflexReceiptIds", "version"],
    optional: ["knowledgeCommitRoot", "knowledgeImageRoot"],
  },
  "knolo.infer.sampler-plan": {
    required: [
      "eosTokenIds",
      "extensions",
      "frequencyPenaltyMicros",
      "kind",
      "maxOutputTokens",
      "minPMillionths",
      "presencePenaltyMicros",
      "processingOrder",
      "repetitionPenaltyMicros",
      "rng",
      "stopStringRoots",
      "temperatureMicros",
      "tieBreak",
      "topK",
      "topPMillionths",
      "version",
    ],
    optional: ["seed", "stream"],
  },
  "knolo.infer.grammar-plan": {
    required: ["enabled", "extensions", "format", "kind", "sourceRoot", "version"],
    optional: [],
  },
  "knolo.infer.inference-intent": {
    required: ["extensions", "kind", "limitsRoot", "modelRuntimeRoot", "promptPlanRoot", "requestedMode", "samplerPlanRoot", "version"],
    optional: ["evidenceBindingRoot", "grammarPlanRoot"],
  },
  "knolo.infer.execution-plan": {
    required: [
      "extensions",
      "intentRoot",
      "kernelPlanRoot",
      "kind",
      "kvBlockSize",
      "mode",
      "placementRoot",
      "prefillChunkTokens",
      "prefixCache",
      "receiptPolicy",
      "schedulingMode",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.inference-event": {
    required: ["attempt", "extensions", "kind", "name", "payloadRoot", "requestId", "version"],
    optional: ["previousEventRoot"],
  },
  "knolo.infer.inference-receipt": {
    required: [
      "assurance",
      "engine",
      "execution",
      "extensions",
      "hardware",
      "intentRoot",
      "kind",
      "model",
      "output",
      "placement",
      "prompt",
      "receiptId",
      "sampler",
      "signatures",
      "timing",
      "version",
    ],
    optional: ["knowledge", "previousReceiptRoot"],
  },
  "knolo.infer.replay-check": {
    required: [
      "assurance",
      "engineBuildRoot",
      "extensions",
      "kind",
      "matched",
      "mismatches",
      "outputTokenRoot",
      "placementRoot",
      "receiptRoot",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.model-conformance": {
    required: [
      "adapterId",
      "engineBuildRoot",
      "extensions",
      "greedyTokenParity",
      "kind",
      "logitAbsToleranceMillionths",
      "modelRuntimeRoot",
      "notesRoot",
      "supportLevel",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.conversion-receipt": {
    required: [
      "conversionConfigRoot",
      "converterBuildRoot",
      "destinationArtifactRoot",
      "extensions",
      "kind",
      "sourceArtifactRoot",
      "validationResult",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.memory-estimate": {
    required: [
      "declaredKvBytes",
      "declaredMarginBytes",
      "declaredOverheadBytes",
      "declaredStagingBytes",
      "declaredTotalBytes",
      "declaredWeightBytes",
      "declaredWorkspaceBytes",
      "estimatorBuildRoot",
      "extensions",
      "headroomBytes",
      "kind",
      "measuredKvBytes",
      "measuredOverheadBytes",
      "measuredStagingBytes",
      "measuredTotalBytes",
      "measuredWeightBytes",
      "measuredWorkspaceBytes",
      "placementRoot",
      "validationResult",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.finalization-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "decodeTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "finalizationLatencyNanos",
      "finalizedNanos",
      "finishReason",
      "kind",
      "modelImageRoot",
      "outputTokenRoot",
      "placementRoot",
      "prefillTokens",
      "promptTokenRoot",
      "receiptRoot",
      "requestCount",
      "runCount",
      "terminalNanos",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.load-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "modelLoadNanos",
      "placementRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.peak-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "device",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "peakRamBytes",
      "peakVramBytes",
      "placementRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.kv-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "pageSizeTokens",
      "pageTotal",
      "peakPages",
      "peakTokens",
      "placementRoot",
      "requestCount",
      "runCount",
      "utilizationMillionths",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.prefix-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "hitCount",
      "kind",
      "lookupCount",
      "missCount",
      "modelImageRoot",
      "placementRoot",
      "requestCount",
      "reusedTokens",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.llama-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "contextTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "hardwareProbeRoot",
      "kind",
      "modelImageRoot",
      "outputDistributionRoot",
      "placementRoot",
      "promptDistributionRoot",
      "quantization",
      "referenceArtifactRoot",
      "referenceBuildRoot",
      "referenceFamily",
      "referenceHardwareRoot",
      "referenceOutputDistributionRoot",
      "referencePromptDistributionRoot",
      "referenceQuantization",
      "referenceRuntime",
      "referenceSamplerRoot",
      "referenceTemplateRoot",
      "referenceTokenizerRoot",
      "referenceVerificationClass",
      "requestCount",
      "runCount",
      "samplerRoot",
      "templateRoot",
      "tokenizerRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.vllm-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "contextTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "hardwareProbeRoot",
      "kind",
      "modelImageRoot",
      "outputDistributionRoot",
      "placementRoot",
      "promptDistributionRoot",
      "quantization",
      "referenceArtifactRoot",
      "referenceBuildRoot",
      "referenceFamily",
      "referenceHardwareRoot",
      "referenceOutputDistributionRoot",
      "referencePromptDistributionRoot",
      "referenceQuantization",
      "referenceRuntime",
      "referenceSamplerRoot",
      "referenceTemplateRoot",
      "referenceTokenizerRoot",
      "referenceVerificationClass",
      "requestCount",
      "runCount",
      "samplerRoot",
      "templateRoot",
      "tokenizerRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.mistral-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "contextTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "hardwareProbeRoot",
      "kind",
      "modelImageRoot",
      "outputDistributionRoot",
      "placementRoot",
      "promptDistributionRoot",
      "quantization",
      "referenceArtifactRoot",
      "referenceBuildRoot",
      "referenceFamily",
      "referenceHardwareRoot",
      "referenceOutputDistributionRoot",
      "referencePromptDistributionRoot",
      "referenceQuantization",
      "referenceRuntime",
      "referenceSamplerRoot",
      "referenceTemplateRoot",
      "referenceTokenizerRoot",
      "referenceVerificationClass",
      "requestCount",
      "runCount",
      "samplerRoot",
      "templateRoot",
      "tokenizerRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.recipe-report": {
    required: [
      "adapterId",
      "artifactRoot",
      "benchmarkRoot",
      "cachePolicy",
      "concurrency",
      "conformanceRoot",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "placementRoot",
      "requestCount",
      "runCount",
      "securityRoot",
      "stabilityRoot",
      "supportLevel",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.composition-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "contextRoot",
      "engineBuildRoot",
      "evidenceRoot",
      "executionMode",
      "extensions",
      "kind",
      "knowledgeCommitRoot",
      "knowledgeImageRoot",
      "modelImageRoot",
      "orderedEvidenceCount",
      "placementRoot",
      "queryReceiptCount",
      "reflexReceiptCount",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.agent-effect-report": {
    required: [
      "allowedExecutionModes",
      "artifactRoot",
      "assurance",
      "backend",
      "cachePolicy",
      "concurrency",
      "decision",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "knowledgeImageRoot",
      "maxOutputTokens",
      "maxPromptTokens",
      "modelImageRoot",
      "modelRuntimeRoot",
      "outputTokens",
      "placementRoot",
      "promptTokens",
      "reason",
      "receiptPresent",
      "requestCount",
      "requiredArtifactRoot",
      "requiredAssurance",
      "requiredKnowledgeImageRoot",
      "requiredModelRuntimeRoot",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.hub-report": {
    required: [
      "adapterId",
      "artifactRoot",
      "benchmarkRoot",
      "cachePolicy",
      "concurrency",
      "conformanceRoot",
      "distribution",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "greedyTokenParity",
      "kind",
      "licenseId",
      "modelImageRoot",
      "nativeSupported",
      "placementRoot",
      "publisher",
      "quantization",
      "requestCount",
      "runCount",
      "sourceProvider",
      "supportLevel",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.chain-report": {
    required: [
      "artifactRoot",
      "assurance",
      "cachePolicy",
      "concurrency",
      "effectRoot",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "finishReason",
      "kernelBundleRoot",
      "kind",
      "knowledgeCommitRoot",
      "knowledgeImageRoot",
      "linkCount",
      "modelRuntimeRoot",
      "outputTextRoot",
      "outputTokenCount",
      "outputTokenRoot",
      "placementRoot",
      "promptTokenCount",
      "promptTokenRoot",
      "queryReceiptCount",
      "queryReceiptRoot",
      "receiptRoot",
      "reflexReceiptCount",
      "reflexReceiptRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.evidence-output-report": {
    required: [
      "assurance",
      "cachePolicy",
      "chainRoot",
      "concurrency",
      "evidenceRoot",
      "executionMode",
      "extensions",
      "finishReason",
      "kind",
      "knowledgeImageRoot",
      "outputTextRoot",
      "outputTokenCount",
      "outputTokenRoot",
      "promptTokenCount",
      "queryReceiptRoot",
      "receiptRoot",
      "reflexReceiptRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.install-report": {
    required: [
      "artifactCount",
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "licenseId",
      "modelImageRoot",
      "placementRoot",
      "publisher",
      "requestCount",
      "runCount",
      "sourceProvider",
      "templateRoot",
      "tokenizerRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.notice-report": {
    required: [
      "cachePolicy",
      "candleNamed",
      "componentCount",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "featureSet",
      "kind",
      "noticeRoot",
      "placementRoot",
      "requestCount",
      "runCount",
      "sbomRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.release-report": {
    required: [
      "binarySetRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "noticeRoot",
      "placementRoot",
      "requestCount",
      "runCount",
      "sbomRoot",
      "signatureCount",
      "signatureStatus",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.binary-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "placementRoot",
      "requestCount",
      "runCount",
      "supervisorBytes",
      "supervisorHash",
      "supervisorName",
      "validationResult",
      "version",
      "warmState",
      "workerBytes",
      "workerHash",
      "workerName",
    ],
    optional: [],
  },
  "knolo.infer.reproducible-report": {
    required: [
      "buildProfile",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "featureSet",
      "instructionCount",
      "kind",
      "lockRoot",
      "placementRoot",
      "requestCount",
      "runCount",
      "sourceRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.signature-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "keyId",
      "keyVerified",
      "kind",
      "placementRoot",
      "releaseRoot",
      "requestCount",
      "runCount",
      "signatureBytes",
      "signatureCount",
      "signatureStatus",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.host-key-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "hostKeyRoot",
      "keyId",
      "keyMaterialPresent",
      "keyVerified",
      "kind",
      "placementRoot",
      "releaseRoot",
      "requestCount",
      "runCount",
      "signatureBytes",
      "signatureStatus",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.receipt-key-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "custody",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "keyId",
      "keyMaterialSerialized",
      "kind",
      "placementRoot",
      "previousKeyId",
      "receiptRoot",
      "requestCount",
      "rotation",
      "runCount",
      "signatureBytes",
      "signatureStatus",
      "trustedMetadata",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.sandbox-report": {
    required: [
      "arguments",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "memoryLimitBytes",
      "modelCas",
      "network",
      "parentDeath",
      "placementRoot",
      "processGroup",
      "requestCount",
      "runCount",
      "scratch",
      "seccomp",
      "sharedMemoryBytes",
      "userClass",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.api-report": {
    required: [
      "auth",
      "bind",
      "bodyLimitBytes",
      "cachePolicy",
      "concurrency",
      "concurrencyLimit",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "metricsLabels",
      "placementRoot",
      "promptLog",
      "ratePerMinute",
      "remoteExplicit",
      "requestCount",
      "runCount",
      "tenantRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.cache-channel-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "crossTenant",
      "engineBuildRoot",
      "executionMode",
      "existenceDisclosure",
      "extensions",
      "kind",
      "metricsScope",
      "placementRoot",
      "prefixAllocated",
      "projectRoot",
      "requestCount",
      "runCount",
      "sharingPolicy",
      "tenantRoot",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.equation-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "equationEvaluated",
      "equationStatus",
      "executionMode",
      "extensions",
      "keyMaterialPresent",
      "kind",
      "messageRoot",
      "placementRoot",
      "publicKeyBytes",
      "releaseRoot",
      "requestCount",
      "runCount",
      "signatureBytes",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.safe-error-report": {
    required: [
      "attempt",
      "cachePolicy",
      "code",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "message",
      "partialReceipt",
      "placementRoot",
      "promptPresent",
      "requestCount",
      "requestId",
      "retryable",
      "runCount",
      "secretPresent",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.redaction-report": {
    required: [
      "alias",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "format",
      "kind",
      "output",
      "path",
      "placementRoot",
      "prompt",
      "promptPlanRoot",
      "receiptRoot",
      "redacted",
      "requestCount",
      "requestId",
      "runCount",
      "stage",
      "tokenIds",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.curve-report": {
    required: [
      "baseMultiplied",
      "cachePolicy",
      "concurrency",
      "curveComputed",
      "curveStatus",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "keyMaterialPresent",
      "kind",
      "messageRoot",
      "placementRoot",
      "pointChecked",
      "publicKeyBytes",
      "releaseRoot",
      "requestCount",
      "runCount",
      "signatureBytes",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.rollback-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "coreLockTouched",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "incomingArtifactRoot",
      "incomingImageRoot",
      "kind",
      "lockfileMutated",
      "placementRoot",
      "previousArtifactRoot",
      "previousImageRoot",
      "reason",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.disconnect-report": {
    required: [
      "cachePolicy",
      "code",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "listenerUp",
      "outcome",
      "outputTokens",
      "placementRoot",
      "promptTokens",
      "requestCount",
      "requestId",
      "runCount",
      "socketClosed",
      "stage",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.receipt-store-report": {
    required: [
      "cachePolicy",
      "code",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "journalEvent",
      "kind",
      "partialReceipt",
      "placementRoot",
      "receiptStored",
      "requestCount",
      "requestId",
      "retryable",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.base-report": {
    required: [
      "baseMultiplied",
      "baseStatus",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "keyMaterialPresent",
      "kind",
      "messageRoot",
      "placementRoot",
      "pointAdded",
      "publicKeyBytes",
      "releaseRoot",
      "requestCount",
      "runCount",
      "scalarBytes",
      "signatureBytes",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.disk-report": {
    required: [
      "cachePolicy",
      "code",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "fileWritten",
      "freeBytes",
      "kind",
      "listenerUp",
      "neededBytes",
      "placementRoot",
      "receiptStored",
      "requestCount",
      "requestId",
      "retryable",
      "runCount",
      "spaceReclaimed",
      "store",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.unload-report": {
    required: [
      "admittedFinished",
      "admittedRequests",
      "cachePolicy",
      "code",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "lifecycle",
      "listenerUp",
      "modelReloaded",
      "placementRoot",
      "queuedRequests",
      "queuedStarted",
      "requestCount",
      "requestId",
      "retryable",
      "runCount",
      "validationResult",
      "version",
      "warmState",
      "workerExited",
    ],
    optional: [],
  },
  "knolo.infer.restart-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "incomingOwnerRoot",
      "journalsSealed",
      "kind",
      "listenerUp",
      "lockReplaced",
      "placementRoot",
      "previousOwnerRoot",
      "processSpawned",
      "reason",
      "requestCount",
      "runCount",
      "secondWorker",
      "validationResult",
      "version",
      "warmState",
      "workerRestartCount",
    ],
    optional: [],
  },
  "knolo.infer.point-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "keyMaterialPresent",
      "kind",
      "messageRoot",
      "placementRoot",
      "pointAdded",
      "pointStatus",
      "pointsEqual",
      "publicKeyBytes",
      "releaseRoot",
      "requestCount",
      "runCount",
      "scalarBytes",
      "signatureBytes",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.duplicate-report": {
    required: [
      "cachePolicy",
      "code",
      "concurrency",
      "duplicateStarted",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "listenerUp",
      "occupantKept",
      "occupantRoot",
      "placementRoot",
      "receiptStored",
      "requestCount",
      "requestId",
      "retryable",
      "runCount",
      "secondJournal",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.concurrent-load-report": {
    required: [
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "inflight",
      "kind",
      "lifecycle",
      "listenerUp",
      "phase",
      "placementRoot",
      "requestCount",
      "restartCount",
      "runCount",
      "secondWorker",
      "validationResult",
      "version",
      "warmState",
      "workerReplaced",
      "workerStarted",
    ],
    optional: [],
  },
  "knolo.infer.eviction-report": {
    required: [
      "activeEvicted",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "evictedPages",
      "evictedTokens",
      "executionMode",
      "extensions",
      "kind",
      "listenerUp",
      "loadRequests",
      "placementRoot",
      "prefixAllocated",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.studio-report": {
    required: [
      "artifactRoot",
      "assurance",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "evidenceRoot",
      "executionMode",
      "extensions",
      "finishReason",
      "kind",
      "knowledgeImageRoot",
      "modelImageRoot",
      "outputTextRoot",
      "outputTokenCount",
      "outputTokenRoot",
      "placementRoot",
      "promptTokenCount",
      "promptTokenRoot",
      "receiptRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.swap-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "incomingLoadNanos",
      "incomingVerificationNanos",
      "kind",
      "modelImageRoot",
      "modelSwapNanos",
      "placementRoot",
      "requestCount",
      "residentArtifactRoot",
      "residentModelImageRoot",
      "runCount",
      "unloadNanos",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.verification-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "modelVerificationNanos",
      "placementRoot",
      "requestCount",
      "runCount",
      "validationResult",
      "verifiedBytes",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.overhead-report": {
    required: [
      "acceptedWriteNanos",
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "decodeTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "finishReason",
      "kind",
      "modelImageRoot",
      "outputTokenRoot",
      "placementRoot",
      "prefillTokens",
      "promptTokenRoot",
      "receiptOverheadNanos",
      "receiptRoot",
      "receiptWriteNanos",
      "requestCount",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.cancellation-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "cancelStage",
      "cancellationLatencyNanos",
      "concurrency",
      "decodeTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "outputTokenRoot",
      "placementRoot",
      "prefillTokens",
      "promptTokenRoot",
      "requestCount",
      "requestedNanos",
      "runCount",
      "terminalNanos",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.fuzz-report": {
    required: [
      "acceptedCount",
      "corpusRoot",
      "distinguishedCount",
      "engineBuildRoot",
      "extensions",
      "kind",
      "mutationCount",
      "rejectedCount",
      "seedCount",
      "targetCount",
      "validationResult",
      "version",
    ],
    optional: [],
  },
  "knolo.infer.latency-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "decodeNanos",
      "decodeTokens",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "latencyP50Nanos",
      "latencyP95Nanos",
      "latencyP99Nanos",
      "modelImageRoot",
      "outputTokenRoot",
      "placementRoot",
      "prefillNanos",
      "prefillTokens",
      "promptTokenRoot",
      "requestCount",
      "requestLatencyNanos",
      "runCount",
      "timePerOutputTokenNanos",
      "timeToFirstTokenNanos",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.throughput-report": {
    required: [
      "artifactRoot",
      "cachePolicy",
      "concurrency",
      "decodeNanos",
      "decodeTokens",
      "decodeTokensPerSecondMicros",
      "engineBuildRoot",
      "executionMode",
      "extensions",
      "kind",
      "modelImageRoot",
      "outputTokenRoot",
      "placementRoot",
      "prefillNanos",
      "prefillTokens",
      "prefillTokensPerSecondMicros",
      "promptTokenRoot",
      "requestCount",
      "requestsPerSecondMicros",
      "runCount",
      "validationResult",
      "version",
      "warmState",
    ],
    optional: [],
  },
  "knolo.infer.perplexity-report": {
    required: [
      "candidateLogitRoot",
      "candidatePerplexityMicros",
      "extensions",
      "greedyParity",
      "kind",
      "maxAbsLogitDeltaMillionths",
      "perplexityDeltaMicros",
      "referenceLogitRoot",
      "referencePerplexityMicros",
      "reporterBuildRoot",
      "targetAccuracyMillionths",
      "targetTokenRoot",
      "tokenCount",
      "validationResult",
      "version",
    ],
    optional: [],
  },
};

export function decodeContract(bytes: Uint8Array): { kind: string; version: bigint } {
  const value = decodeCanonicalCbor(bytes);
  if (!(value instanceof Map)) throw new InferFailure("CONTRACT_INVALID", "contract must be a map");
  const kind = value.get("kind");
  const version = value.get("version");
  if (typeof kind !== "string" || !KINDS[kind]) throw new InferFailure("CONTRACT_INVALID", "unexpected contract kind");
  if (typeof version !== "bigint" || version !== 1n) {
    throw new InferFailure("CONTRACT_INVALID", "unsupported contract version");
  }
  const spec = KINDS[kind];
  const allowed = new Set([...spec.required, ...spec.optional]);
  for (const key of value.keys()) {
    if (!allowed.has(key)) throw new InferFailure("CONTRACT_INVALID", "unknown field");
  }
  for (const key of spec.required) {
    if (!value.has(key)) throw new InferFailure("CONTRACT_INVALID", "missing field");
  }
  return { kind, version };
}

export function isContractMap(value: CborValue): value is Map<string, CborValue> {
  return value instanceof Map && typeof value.get("kind") === "string" && String(value.get("kind")).startsWith("knolo.infer.");
}
